AllCops:
  TargetRubyVersion: 2.2
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/*

Naming/MethodParameterName:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
